### ISSUE TITLE
Faint yellow LEDs

### ISSUE THREAD

**Issue by cahir1987** [fabiosoft/esp8266_ikea_vindriktning#1]
Hi, thanks for your project. Everything is working. I have only problem with weakly lit yellow leds. After lighting them they are very dark light. I cut the path between R3 and R4 only on the length of resistors. Is it supposed to be like this? I measured left legs of resistors and they are not both connected. I did not cut the C1 path to the capacitor and I did not connect the path witch a wire. Do you have any idea what the problem is?

**Comment by fabiosoft** [comment]
Yes, same effect for me... yellow led it's weak.
I suppose there is not enought voltage (although i used a level shifter) due to it's the only one logically not inverted.

Can you measure voltage output and across led?
